import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "코딩하느님, 좋은 일이 가득하게 해주시옵소서. 라멘.",
  description: "Generated by create next app",
};

// HTML 기초를 잡아주는 태그 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <Link href="/">index</Link>
          &nbsp;
          <Link href="/search">search</Link>
          &nbsp;
          <Link href="/book/1">book/1</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
